version: '3'
services:
  server:
    image: golang:1.20.6-bullseye
    volumes:
      - .:/app
    working_dir: /app
    command:
      - /bin/bash
      - -e
      - -x
      - -c
      - |
        if [[ ! -f "/go/bin/air" ]]; then
          go install github.com/cosmtrek/air@v1.44.0
        fi
        air -c .air.toml
  client:
    image: node:18.17.0-alpine3.17
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.angular
    working_dir: /app
    command:
      - /bin/sh
      - -e
      - -x
      - -c
      - |
        npm install
        exec npm start -- \
          --host 0.0.0.0 \
          --poll 1000 \
          --proxy-config proxy.conf.js
    ports:
      - 4200:4200
    depends_on:
      - server
